# Generated by Django 3.2.9 on 2022-04-09 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='./images/user.png', null=True, upload_to='static/images/')),
                ('dob', models.DateField(default='2021-12-01')),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
