# Generated by Django 3.2.8 on 2021-11-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_remove_voucher_product'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='voucher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucher'),
        ),
    ]
