# Generated by Django 3.2.9 on 2021-12-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_comment_comment_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
