# Generated by Django 3.2.9 on 2021-12-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
