# Generated by Django 3.2.9 on 2022-03-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
    ]
