# Generated by Django 3.2.9 on 2021-11-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='product',
            field=models.ForeignKey(default='822e2e7686134e5289fe9e1d4d3e4770', on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
