# Generated by Django 3.2.9 on 2021-11-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('vouchers', '0003_alter_voucher_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
